- cromulent/model.py
- setup.py
- tests/test_model.py
Closes #13 ; Closes #12 
Breadth first solution is not elegant but seems to work. A better (read "real") engineer may have a better solution.
> depth -> breadth ; fix list of strings ; + tests

- cromulent/model.py
- setup.py
add collapse=n to toString() to compact multiple lines into one, until they reach n characters
> Allow line length based string output compaction

- cromulent/data/cidoc-extension.json
- cromulent/data/crm_vocab.tsv
- cromulent/data/linked-art.json
- cromulent/model.py
- setup.py
- utils/data/linkedart_crm_enhancements.xml
- utils/make_jsonld_context.py
Fix context generation, fix mapping of non CRM, non LA classes
> Context, Mapping

- cromulent/model.py
> fix a missing factory.done ref

- cromulent/model.py
- setup.py
... that meant that graphs weren't completely serialized
> Fix recursion bug

- cromulent/vocab.py
To allow pages, books, and anything else to be ordered in a linear sequence
> add numbers, sequence vocab items

- cromulent/model.py
- cromulent/vocab.py
Add a few new Statement types to vocab. Add support for pickling/unpickling a factory.
> Vocab entries for JPGM, pickle support

- cromulent/model.py
- tests/test_model.py
Fix py2/ py3 issue with test for is-a-file. Add a test.
> fix bugs, add test

- cromulent/model.py
- tests/test_model.py
> allow some common URI schemes, plus tests

- cromulent/vocab.py
> add unknown physical dimension

- cromulent/vocab.py
- tests/test_vocab.py
> Update boundary to make procurement a separate call

- cromulent/data/crm-profile.json
- cromulent/data/crm_vocab.tsv
- cromulent/model.py
- cromulent/vocab.py
- tests/test_model.py
- utils/data/linkedart.xml
Place+Thing from: http://lists.ics.forth.gr/pipermail/crm-sig/2019-July/003904.html
Plus add Citation, and allow filtering properties for only ones that are usable
> Add merge class for Place+Thing; additional vocab; filter by profile

- cromulent/extract.py
- tests/test_dimensions.py
Copy-paste from pipeline. `extract_physical_dimensions` is the primary entry-point for the dimension parsing.
> Moved parsing/extraction and modeling code into cromulent.extract

- cromulent/vocab.py
- setup.py
> Archival concept updates

- cromulent/model.py
> Serialize JSON with unescaped non-ascii characters

- cromulent/extract.py
- tests/test_model.py
I missed a couple in the PR yesterday.
> Consistent IDs

- cromulent/extract.py
- tests/test_dimensions.py
* Accept abbreviated "pouc." as a unit
* Accept lone fractional values without an integer part (e.g. "1/2")
* Improve logging of unexpected dimension data
> Improve handling of dimension statement data

- cromulent/extract.py
- tests/test_dimensions.py
> Improve extract.normalize_dimension to handle values with only partial units

- cromulent/extract.py
- cromulent/vocab.py
- tests/test_dimensions.py
Improvements to dimension statement handling:
* Improve the code that recognizes cases where mixed unit systems are used (e.g. metric and imperial)
* Improve the extraction code to recognize more real-world dimension strings (DEV-2729)
> Improvements to dimension statements

- cromulent/vocab.py
Add RGB colorspace and some primary colors to instance table in vocab.
> Color vocab

- cromulent/vocab.py
- tests/test_vocab.py
Add new terms from Patricia
Use Right (for forthcoming refactor of Rights for Provenance) not PropertyInterest
Add make_multitype_obj
> New vocab, make_multitype_obj

- cromulent/vocab.py
One more based on discussion with Kelly.
> Add currency instance for groschen

- cromulent/vocab.py
- setup.py
And a bit of reshuffling and commenting on sections of vocab
> More meta types

- cromulent/vocab.py
> update probably, possible, add former name

- cromulent/vocab.py
What do you think about this for including information about multiple price data in German sales?
> Add vocab.SalePriceStatement for text about selling price

- cromulent/vocab.py
They were in instances, but not the class list.
> Add classes for HMO / Place types

- cromulent/vocab.py
> add vandalism and spraypainting example instances

- cromulent/vocab.py
- tests/test_vocab.py
And add some example vocab entries for transfer of custody.
> fix boundary test after brief text change

- cromulent/model.py
- cromulent/vocab.py
For both getter and setter, with tests.
Optional and ontology specific, so in vocab
> Allow Right.part instead of Right.c_part

- cromulent/vocab.py
Add HumanMadeObjects for catalogs, and add metatypes for their textual counterparts (and similar).
> Catalog types

- cromulent/extract.py
- tests/test_currency.py
* Recognize price values that include commas
* Find referring notes in the 'note' field of the input dict
> Improve price extraction

- cromulent/data/crm-profile.json
- cromulent/data/crm_vocab.tsv
- cromulent/data/linked-art.json
- cromulent/vocab.py
- setup.py
- utils/data/linkedart.xml
Add `represents_instance_of_type` property in the interim of the SIG formalizing it.
> Reps instance

- cromulent/vocab.py
> Add 4 professional activity types

- cromulent/model.py
* Add a JSONEncoder that produces HTMLified JSON via iterencode().  
This would be better by passing in the objects directly, but that's a much larger, longer change.
Advantages to this approach are that we can optimize for JSON-LD constructions within the library, rather than relying on external parsers to do clever things. 
* Add some additional checks to __eq__ for manipulating crom objects in lists with non crom objects.
* Add a list_app_props_with_range function to facilitate random graph generation.
* Add highlight and elide internal fields to resources, that can be later detected to manipulate the output of toHtml()
> Highlight experiment

- cromulent/vocab.py
For time based dimensions, such as a duration
> add seconds, days, years as measurement units

- cromulent/extract.py
Round price amounts to 3 decimal places, and add thousands separator formatting.
> Improve formatting of price labels in extract_monetary_amount

- cromulent/vocab.py
I've included both physical sex and sociological gender under the Gender type, but clearly one could be physically female and sociologically non-binary, so these should not be considered disjoint classes.
> Add genders, sexes from AAT

- cromulent/vocab.py
@azaroth42 I'm doing this as a PR to the Getty repo since the linked art one isn't up to date, and so the PR would pull in the intervening changes. I suggest that this PR be approved, and then the linked art repo merge thegetty/crom@master.
> Add classes and instances for sovereign states and counties.
