thegetty/crom

README.md, cromulent/model.py, cromulent/vocab.py, tests/test_model.py, tests/test_vocab.py
PR takes done off of factory as a property, and passes it around by reference.  Functions that are called as the API need to set it explicitly to a new empty dict, otherwise the VM seems to use the same dict as the previous invocation if it defaults to the param default. (Who knew? Certainly not me)
=> Make serialization recursion tracking threadsafe ... I think

cromulent/model.py, cromulent/multiple_instantiation.py, cromulent/vocab.py, setup.py, tests/test_model.py, tests/test_vocab.py
* Make dir(object) work, such that it reports the magic properties
* Refactor handling of `type` to make object.type (getter) work, and raise for setter
* Refactor `top` handling to allow it to be passed through for determining graph boundary (currently not used, but pretty sure it's needed)
* Implement algorithmic graph boundary test in vocab to keep linked art profile separable from core code, and graph separate from API
* Make `content` an alias for `value` in constructor
* Make use of new `type` magic to fix multiple_instantiation classes (not used in current profile), and simplify resulting `type` serialization
=> Implement requested functionality

cromulent/data/crm_vocab.tsv, utils/data/linkedart.xml
Sets should be able to have rights associated with them - for example I do not have the right to add an item into the collection of the museum, nor to add a concept to the set of terms in AAT. Ed Ruscha and the GRI, conversely, have the right to add objects into the Ruscha archive. This means it needs to be a Legal Object.
Similarly, the Ruscha archive or a set of objects as an exhibition, can be "about" some set of topics.  This means it needs to be a Propositional Object.
The merge point of these is Information Object, but the set is not Symbolic in nature. Thus two super-classes, as above.
=> Make Set subclass of Proposition and Legal

cromulent/vocab.py
Slight refactor to the vocab processing order to allow instances to use the pseudo-classes defined in ext_classes.
Now nationalities come out as:
```
"@context": "https://linked.art/ns/v1/linked-art.json", 
"id": "http://vocab.getty.edu/aat/300107956", 
"type": "Type", 
"_label": "American", 
"classified_as": [
{
"id": "http://vocab.getty.edu/aat/300379842", 
"type": "Type", 
"_label": "Nationality"
}
]
}
```
As described here: https://linked.art/model/actor/#nationality
=> ensure nationality instances are classified as Nationalities

cromulent/model.py, cromulent/vocab.py, tests/test_model.py
Allow `multiple_instances_per_property` setting that governs what to do with a property that has exactly the same resource added to it multiple times.
Split the class list for linked_art_boundary check into different types, as precursor to exposing them to other functions (e.g. merge code)
=> Split embed classes to types, add multiple_instances_per_property

cromulent/extract.py
Prioritize common case, and return early if extraction fails.
This should noticeably help the performance of the sales pipeline which has a lot of price columns.
=> Performance improvements in .extract.extract_monetary_amount

cromulent/model.py, cromulent/vocab.py, tests/test_model.py
(plus a couple vocab tweaks that were lying around)
Profiling stats:
Without cache and with validation:
```        1    0.090    0.090    1.527    1.527 profile_test.py:8(make_a_thing)```
With cache and without validation:
```        1    0.075    0.075    1.160    1.160 profile_test.py:8(make_a_thing)```
=> factory.production_mode() turns off checking and caches class hierarchy

cromulent/extract.py, cromulent/vocab.py, tests/test_dimensions.py
This does two things:
* Differentiates French and imperial feet and inches (previously these were treated the same)
* Adds support for French `lignes`
When/if `cromulent.vocab.instances` gains a `fr_inches` entry, results from `cromulent.extract.extract_physical_dimensions` on data using French units should automatically gain unit assertions.
=> French units

cromulent/vocab.py
This is not meant to be instantiated directly, but is useful for code in [pipeline](http://github.com/thegetty/pipeline) that tests if an object is classified as `BriefText`.
=> Add vocab._BriefText.

cromulent/extract.py
This was causing the currency of some price data to go unrecognized.
=> Fix extraction of monetary amounts that use currency names of mixed case

cromulent/extract.py
In cases where we need special handling to get the citations data modeled correctly, `extract_monetary_amount` can be told to ignore the citations when constructing `MonetaryAmount` objects.
=> Only add bibliographic references to MonetaryAmounts if requested

cromulent/vocab.py
I need to confirm that some of these are the right currencies to align with GRI data, but they seem reasonable to have in vocab either way.
=> Added new currency instances

cromulent/extract.py, tests/test_currency.py, tests/test_dimensions.py
`extract_monetary_amount` can now take a mapping table as an argument instead of having hard-coded currency data in `cromulent.extract`. This will allow the pipeline code to pass in per-project currency mapping data.
=> Improve extract_monetary_amount and add related tests.

cromulent/extract.py
Allow price data to be in the `amount` key of the supplied dict.
=> Allow extract_monetary_amount to extract more price information.

cromulent/data/linked-art.json, cromulent/vocab.py, utils/make_jsonld_context.py
* Make `assigned_property` `@type: @vocab` so it picks up the context (typo in the field in the builder)
* Make `assigned_property` only test when the subject of the triple is valid
* Add a "contribution" aat entry for examples of Production/Creation part classifications
=> Assigned prop vocab

cromulent/vocab.py
Per discussion in https://github.com/linked-art/linked.art/issues/296, it is more consistent to have brief-text as a metatype for the statement types, rather than as a sibling.
This change puts that in effect.
=> Brief meta type

cromulent/vocab.py, tests/test_vocab.py
@kasei Note well that this renames `Procurement` to `ProvenanceEntry`.  Saying that losing an object was a procurement was too galling!
Also adds terms from Patricia, and placeholder for sale of stolen goods.
=> add more provenance terms

cromulent/reader.py, cromulent/vocab.py, tests/test_reader.py, tests/test_vocab.py
Reader now  works with add_attribute_assignment and conceptual parts.
Also creates instances of vocab "extension" classes,  rather than vanilla classes  from the  model with the right classifications.
This is important for boundary checking, in case the test looks for the vocab class, rather than the classification.
Also fix some edge cases revealed by testing the reader on all the examples in linked art site, and add tests.
=> Improve reader, fix some tests

cromulent/reader.py
This fixes a bug where the loop in reader that tries to compare with every instance in `dir(vocab)` ends up finding values that are not instances (e.g. `STR_TYPES`).
=> Fix bug in reader classification code.

cromulent/vocab.py
As mentioned, the previous PR that added these as People was a mistake. These are not classifications of people, but of the role those people play in the event.
=> Replace people with activities for French roles of Expert/CommissairePriseur

cromulent/model.py
Current implementation sorts the keys twice :( This adds the factory.order_json flag around the first sort as well as the second, but the implementation of toJSON should be improved as well.
=> add order_json flag around first sort

cromulent/model.py, tests/test_model.py
Add a Python3 only serializer that relies on 3.7+ dicts being ordered.
Reduces the time to serialize by about 40%.
Need to set factory.json_serializer to "fast" to enable this.
Also:
* fixes some production_mode issues.
* adds a "off" flag to production_mode to reset the flags (but can't un-cache the hierarchy)
* put a test around required properties for validation
=> Performance improvements

cromulent/vocab.py
To align with digitalimage, and make digitally_carried_by work consistently with other references to web content.
=> web page should be digital
